name: first_flutter_app
description: A new Flutter application.rl u ca

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  background_fetch: ^0.2.0
  audioplayers: ^0.13.2
  rflutter_alert: ^1.0.3
  font_awesome_flutter: ^8.5.0
  flushbar: ^1.9.1
  flare_splash_screen: ^3.0.0
  camera: ^0.5.6+3
  video_player: ^0.10.2+5
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: BreeSerif
      fonts:
        - asset: assets/fonts/BreeSerif-Regular.ttf

    - family: Cursive
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
        - asset: assets/fonts/Cookie-Regular.ttf
